import Head from 'next/head';
import Page from '../components/Page';
import NavPanel from '../components/NavPanel';
import Footer from '../components/Footer';

export default function Home() {
  return (
    <div>
		<Head>
			<title>Criando app nextjs</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>

		<Page>

			<section>
				<NavPanel />
				<main>
					Conteúdo
				</main>
			</section>

			<Footer />
		</Page>
		

		
    </div>
  )
}
